#-----------------------------------------------------------------------------------
.PHONY: clean syn
syn:
	synplify -batch wujian100_open_200t_3b.prj

clean:
	rm -rf *.log FDC_constraints wujian100_open_200t_3b_rev *.tcl *.prd stdout.log*

#-----------------------------------------------------------------------------------
