#-----------------------------------------------------------------------------------
.PHONY: clean

# genrated bit file
bit:
	vivado -mode tcl -source wujian100_open_200t_3b_prj.tcl	

clean:
	rm -rf *.jou *.log project_3b

#-----------------------------------------------------------------------------------
